# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from luisd.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    AGGREGATION = "Aggregation"
    ALLOCATIONS = "Allocations"
    APPLICATION_METADATA = "Application Metadata"
    BLOCKS = "Blocks"
    CALENDARS = "Calendars"
    COMPLEX_MARKET_DATA = "Complex Market Data"
    COMPLIANCE = "Compliance"
    CONFIGURATION_RECIPE = "Configuration Recipe"
    CONVENTIONS = "Conventions"
    CORPORATE_ACTION_SOURCES = "Corporate Action Sources"
    COUNTERPARTIES = "Counterparties"
    CUSTOM_ENTITIES = "CustomEntities"
    CUSTOM_ENTITY_DEFINITIONS = "CustomEntityDefinitions"
    CUT_LABEL_DEFINITIONS = "Cut Label Definitions"
    DATA_TYPES = "Data Types"
    DERIVED_TRANSACTION_PORTFOLIOS = "Derived Transaction Portfolios"
    ENTITIES = "Entities"
    EXECUTIONS = "Executions"
    FEES_AND_COMMISSIONS = "FeesAndCommissions"
    INSTRUMENTS = "Instruments"
    LEGAL_ENTITIES = "Legal Entities"
    ORDER_GRAPH = "OrderGraph"
    ORDER_INSTRUCTIONS = "OrderInstructions"
    ORDERS = "Orders"
    PACKAGES = "Packages"
    PARTICIPATIONS = "Participations"
    PERSONS = "Persons"
    PLACEMENTS = "Placements"
    PORTFOLIO_GROUPS = "Portfolio Groups"
    PORTFOLIOS = "Portfolios"
    PROPERTY_DEFINITIONS = "Property Definitions"
    QUOTES = "Quotes"
    RECONCILIATIONS = "Reconciliations"
    REFERENCE_PORTFOLIO = "Reference Portfolio"
    RELATION_DEFINITIONS = "Relation Definitions"
    RELATIONS = "Relations"
    RELATIONSHIP_DEFINITIONS = "Relationship Definitions"
    RELATIONSHIPS = "Relationships"
    SCHEMAS = "Schemas"
    SCOPES = "Scopes"
    SEARCH = "Search"
    SEQUENCES = "Sequences"
    STRUCTURED_RESULT_DATA = "Structured Result Data"
    SYSTEM_CONFIGURATION = "System Configuration"
    TRANSACTION_PORTFOLIOS = "Transaction Portfolios"
    TRANSLATION = "Translation"
